# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/hands_on_ml_learn',
                'doc_host': 'https://navc90.github.io',
                'git_url': 'https://github.com/navc90/hands_on_ml_learn',
                'lib_path': 'hands_on_ml_learn'},
  'syms': { 'hands_on_ml_learn.Ch2_EndToEnd': { 'hands_on_ml_learn.Ch2_EndToEnd.create_train_test_split': ( 'core.html#create_train_test_split',
                                                                                                            'hands_on_ml_learn/Ch2_EndToEnd.py'),
                                                'hands_on_ml_learn.Ch2_EndToEnd.describe_percentiles': ( 'core.html#describe_percentiles',
                                                                                                         'hands_on_ml_learn/Ch2_EndToEnd.py'),
                                                'hands_on_ml_learn.Ch2_EndToEnd.is_id_in_test_set': ( 'core.html#is_id_in_test_set',
                                                                                                      'hands_on_ml_learn/Ch2_EndToEnd.py'),
                                                'hands_on_ml_learn.Ch2_EndToEnd.load_housing_data': ( 'core.html#load_housing_data',
                                                                                                      'hands_on_ml_learn/Ch2_EndToEnd.py')},
            'hands_on_ml_learn.core': {'hands_on_ml_learn.core.foo': ('core.html#foo', 'hands_on_ml_learn/core.py')}}}
