# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello', 'load_housing_data']

# %% ../nbs/00_core.ipynb 3
def foo():
    pass

# %% ../nbs/00_core.ipynb 4
def say_hello(to):
    "say hello to somebody"
    return f"Hello {to}!"

# %% ../nbs/00_core.ipynb 8
def load_housing_data():
    "loads california housing data needed for this project"
    tarball_path = Path("datasets/housing.tgz")
    if not tarball_path.is_file():
        Path("datasets").mkdir(parents=True, exist_ok=True)
        url = "https://github.com/ageron/data/raw/main/housing.tgz"
        urllib.request.urlretrieve(url, tarball_path)
        with tarfile.open(tarball_path) as housing_tarball:
            housing_tarball.extractall(path="datasets")

    return pd.read_csv(Path("datasets/housing/housing.csv"))
